version: '3.8'


services:
  app:
    build: .
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
    user: "1000"
    env_file:
      - .env
    environment:
      - NAME=${NAME:-Luis}
